name: compilar y desplegar
on:
  push:
    branches:
      - main
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Despliegue de la aplicación Angular en la rama gh-pages
      uses: AhsanAyaz/angular-deploy-gh-pages-action@v1.3.2
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: production
        base_href: /WeRunning/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/WeRunning
